version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    ignore:
      - package: "react"
        version: "*"
      - package: "react-dom"
        version: "*"
      - package: "react-scripts"
        version: "*"
