name: "Call: Deploy stage"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted ]
    environment:
      name: stage
      url: 'https://test.creaty.club'
    steps:
    - name: Deploy stage environment
      run: |
        cd /home/www/runner/work/creaty-api/creaty-api
        sudo docker-compose -f docker/stage/docker-compose.stage.yml up --build -d
