name: "Call: build"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: 'latest'
      push:
        type: boolean
        required: false
        default: true
      environ:
        type: string
        required: false
        default: 'dev'
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: 'latest'
      push:
        type: boolean
        required: false
        default: true
      environ:
        type: string
        required: false
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Login to container registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          repository=${{ github.repository }}
          echo "REPOSITORY=${repository,,}" >> ${GITHUB_ENV}
      - name: Set stage env
        if: ${{ inputs.environ == 'dev' }}
        run: |
          echo "${{ secrets.DEV_ENV }}" > .env
      - name: Set stage env
        if: ${{ inputs.environ == 'stage' }}
        run: |
          echo "${{ secrets.STAGE_ENV }}" > .env
      - name: Set prod env
        if: ${{ inputs.environ == 'prod' }}
        run: |
          echo "${{ secrets.PROD_ENV }}" > .env
      - name: Build and push docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ env.REPOSITORY }}/web:${{ inputs.tag }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPOSITORY }}/web:${{ inputs.tag }}
          cache-to: type=inline
