name: "Call: build"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: 'latest'
      push:
        type: boolean
        required: false
        default: true
      environment:
        type: string
        required: false
        default: 'dev'
      url:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: 'latest'
      push:
        type: boolean
        required: false
        default: true
      environment:
        type: string
        required: false
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Login to container registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          repository=${{ github.repository }}
          echo "REPOSITORY=${repository,,}" >> $GITHUB_ENV
      - name: Set variables
        run: |
          variable_keys=(
            "REACT_APP_API_CACHE"
            "REACT_APP_API_CACHE_TIME"
            "REACT_APP_API_HOST"
          )
          vars_json='${{ toJSON(vars) }}'
          for key in "${variable_keys[@]}"; do
            value=$(echo $vars_json | jq -r --arg key "$key" '.[$key]')
            if [ "$value" != "null" ]; then
              echo $key=$value >> .env
            fi
          done
      - name: Set secrets
        env:
          REACT_APP_API_GA: ${{ secrets.REACT_APP_API_GA }}
        run: |
          secret_keys=(
            "REACT_APP_API_GA"
          )
          for key in ${secret_keys[@]}; do
            value=$(echo "${!key}")
            if [[ -z "$value" ]]; then
              echo "$key is not defined"
              exit 1
            fi
            echo "$key=$value" >> .env
          done
      - name: Build and push docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ env.REPOSITORY }}/web:${{ inputs.tag }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPOSITORY }}/web:${{ inputs.tag }}
          cache-to: type=inline
