name: CI

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
        default: latest
      push:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Login to container registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          repository=${{ github.repository }}
          echo "REPOSITORY=${repository,,}" >> ${GITHUB_ENV}
      - name: Build and push docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ env.REPOSITORY }}/web:${{ inputs.tag }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPOSITORY }}/web:${{ inputs.tag }}
          cache-to: type=inline
