name: "Call: Deploy stage"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: stage
      url: 'http://stage.creaty.club:81'
    steps:
      - name: Pull web docker image
        run: docker pull ghcr.io/creaty-co/creaty-web/web:latest
      - name: Deploy stage environment
        run: |
          cd /home/www/runner/work/creaty-api/creaty-api
          docker-compose -f docker/stage/docker-compose.stage.yml up --build -d
