name: "Push: not main"

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  ci:
    uses: ./.github/workflows/call-build.yml
    with:
      environment: dev
      push: false
    secrets: inherit
