name: "Push: main"

on:
  push:
    branches:    
      - 'main'

jobs:
  ci:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/call-deploy_dev.yml
    needs: [ ci ]
