name: "Release: published"

on:
  release:
    types: [ published ]

jobs:
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
  build_stage:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      tag: pre-${{ github.ref_name }}
      environment: stage
      url: 'https://stage.creaty.club'
  build_prod:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
      environment: prod
      url: 'https://creaty.club'
