name: "Release: pre release"

on:
  release:
    types: [ published ]

jobs:
  build:
    if: "github.event.release.prerelease"
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
      environment: stage
      url: 'https://stage.creaty.club'
