name: "Release: published"

on:
  release:
    types: [ published ]

jobs:
  build:
    if: "!github.event.release.prerelease"
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
      environ: 'prod'
